
const D=window.MONEYCOIN_DATA,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const OVERVIEW_PERIODS={Hoje:[177547,177120,176880,176430,176820,176210,175990,176140,175720,175842],"5D":[173900,174420,174080,175110,175620,174980,176240,175770,176910,175842],"1M":[168500,169830,171200,170650,172900,174200,173550,176300,175100,175842],"6M":[158400,161700,160900,165200,168600,166800,171500,173200,172400,175842],"1A":[143800,149400,151900,148700,156300,161800,164200,169700,172500,175842]};let activeOverviewPeriod="Hoje";function renderOverviewPeriod(period){activeOverviewPeriod=period;const v=OVERVIEW_PERIODS[period]||OVERVIEW_PERIODS.Hoje;$('#overviewChart').innerHTML=svgLine(v,v[v.length-1]>=v[0]?'#149c53':'#df3b43')}let current='overview',lastView='overview',simStep=0,simulationTimer;
const fmt=(v,d=2)=>Number(v).toLocaleString('pt-BR',{minimumFractionDigits:d,maximumFractionDigits:d});const compact=v=>v>=1e9?(v/1e9).toFixed(1)+' bi':v>=1e6?(v/1e6).toFixed(1)+' mi':fmt(v,0);
function chartHover(event,svg){
 const values=(svg.dataset.values||'').split(',').map(Number);if(!values.length)return;
 const rect=svg.getBoundingClientRect(),vb=svg.viewBox.baseVal,w=vb.width||700,h=vb.height||260,p=20;
 const clientX=event.touches?event.touches[0].clientX:event.clientX;
 const ratio=Math.max(0,Math.min(1,(clientX-rect.left)/rect.width));
 const index=Math.max(0,Math.min(values.length-1,Math.round(ratio*(values.length-1))));
 const min=Math.min(...values),max=Math.max(...values),range=max-min||1;
 const x=p+index*(w-2*p)/(values.length-1),y=h-p-(values[index]-min)*(h-2*p)/range;
 const guide=svg.querySelector('.hover-guide'),dot=svg.querySelector('.hover-dot'),label=svg.querySelector('.hover-label'),text=svg.querySelector('.hover-text'),box=svg.querySelector('.hover-box');
 guide.setAttribute('x1',x);guide.setAttribute('x2',x);dot.setAttribute('cx',x);dot.setAttribute('cy',y);
 const formatted=values[index].toLocaleString('pt-BR',{maximumFractionDigits:values[index]<100?2:0});text.textContent=formatted;
 const labelWidth=Math.max(82,formatted.length*8+22),labelX=Math.max(4,Math.min(w-labelWidth-4,x-labelWidth/2)),labelY=Math.max(5,y-47);
 label.setAttribute('transform',`translate(${labelX} ${labelY})`);box.setAttribute('width',labelWidth);text.setAttribute('x',labelWidth/2);
 svg.classList.add('is-hovered');
}
function chartLeave(svg){svg.classList.remove('is-hovered')}
function svgLine(data,color='#149c53',fill=true){
 const w=700,h=260,p=20,min=Math.min(...data),max=Math.max(...data),range=max-min||1;
 const pts=data.map((v,i)=>`${p+i*(w-2*p)/(data.length-1)},${h-p-(v-min)*(h-2*p)/range}`).join(' ');
 const gid='g'+Math.random().toString(36).slice(2,9);
 return `<svg class="interactive-line-chart" data-values="${data.join(',')}" viewBox="0 0 ${w} ${h}" preserveAspectRatio="none" onmousemove="chartHover(event,this)" ontouchmove="chartHover(event,this)" onmouseleave="chartLeave(this)" ontouchend="chartLeave(this)"><defs><linearGradient id="${gid}" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="${color}" stop-opacity=".23"/><stop offset="1" stop-color="${color}" stop-opacity="0"/></linearGradient></defs>${fill?`<polygon points="${p},${h-p} ${pts} ${w-p},${h-p}" fill="url(#${gid})"/>`:''}<polyline points="${pts}" fill="none" stroke="${color}" stroke-width="2.4" vector-effect="non-scaling-stroke"/><line class="hover-guide" y1="${p}" y2="${h-p}"/><circle class="hover-dot" r="5" fill="${color}"/><g class="hover-label"><rect class="hover-box" height="32" width="90"/><text class="hover-text" x="45" y="21" text-anchor="middle">0</text></g></svg>`
}
function mini(data,color='#149c53'){return svgLine(data,color,false)}
function candles(data){let out='<svg viewBox="0 0 700 260" preserveAspectRatio="none">';const min=Math.min(...data)*.997,max=Math.max(...data)*1.003,scale=v=>240-(v-min)/(max-min)*220;for(let i=1;i<data.length;i++){let o=data[i-1],c=data[i],hi=Math.max(o,c)*(1+.0015),lo=Math.min(o,c)*(1-.0015),x=20+i*660/(data.length-1),col=c>=o?'#149c53':'#df3b43';out+=`<line x1="${x}" y1="${scale(hi)}" x2="${x}" y2="${scale(lo)}" stroke="${col}" stroke-width="1"/><rect x="${x-4}" y="${Math.min(scale(o),scale(c))}" width="8" height="${Math.max(2,Math.abs(scale(c)-scale(o)))}" fill="${col}" rx="1"/>`}return out+'</svg>'}
function showSkeleton(target,callback){const el=$(target);el.innerHTML='<div class="skeleton" style="height:42px;margin:8px"></div>'.repeat(6);setTimeout(callback,420)}
function simpleRows(list,kind='stock'){return `<div class="simple-head"><span>Ativo</span><span class="right">Preço</span><span class="right">Var.</span></div>`+list.map(x=>`<div class="simple-row clickable" data-detail="${kind}:${x.ticker||x.symbol}"><b>${x.ticker||x.symbol}</b><span class="right">${kind==='stock'?'R$ ':''}${fmt(x.price,x.price<1?6:2)}</span><span class="right ${x.change>=0?'positive':'negative'}">${x.change>=0?'+':''}${fmt(x.change)}%</span></div>`).join('')}
function renderOverview(){renderOverviewPeriod(activeOverviewPeriod);const sorted=[...D.stocks].sort((a,b)=>b.change-a.change);$('#topGainers').innerHTML=simpleRows(sorted.slice(0,5));$('#topLosers').innerHTML=simpleRows(sorted.slice(-5).reverse());$('#mostTraded').innerHTML=simpleRows([...D.stocks].sort((a,b)=>b.volume-a.volume).slice(0,5));$('#featuredCrypto').innerHTML=simpleRows(D.cryptos.slice(0,5),'crypto');$('#featuredNews').innerHTML='<div class="news-mini">'+D.news.slice(0,3).map(n=>`<a href="${n.url}" target="_blank" rel="noopener noreferrer"><img src="assets/news/${n.image}"><div><h3>${n.title}</h3><p>${n.source} · ${n.time}</p></div></a>`).join('')+'</div>'}
function stockRows(list){return `<div class="asset-head"><span>Ativo</span><span>Empresa</span><span>Preço</span><span>Variação</span><span>Volume</span><span>DY</span><span></span></div>`+list.map(s=>`<div class="asset-row" data-detail="stock:${s.ticker}"><div class="asset-name"><i class="asset-logo">${s.ticker.slice(0,2)}</i><div><b>${s.ticker}</b><small>${s.sector}</small></div></div><span>${s.name}</span><b>R$ ${fmt(s.price)}</b><b class="${s.change>=0?'positive':'negative'}">${s.change>=0?'+':''}${fmt(s.change)}%</b><span>${compact(s.volume)}</span><span>${fmt(s.dy)}%</span><img class="arrow-icon" src="assets/chevron.svg"></div>`).join('')}
function cryptoRows(list){return `<div class="asset-head"><span>Ativo</span><span>Nome</span><span>Preço</span><span>Variação</span><span>Capitalização</span><span>Volume</span><span></span></div>`+list.map(c=>`<div class="asset-row" data-detail="crypto:${c.symbol}"><div class="asset-name"><img class="crypto-logo" src="assets/crypto/${c.symbol.toLowerCase()}.svg" onerror="this.onerror=null;this.src='assets/crypto/default.svg'" alt="${c.name}"><div><b>${c.symbol}</b><small>Cripto</small></div></div><span>${c.name}</span><b>R$ ${fmt(c.price,c.price<1?6:2)}</b><b class="${c.change>=0?'positive':'negative'}">${c.change>=0?'+':''}${fmt(c.change)}%</b><span>R$ ${fmt(c.marketCap,1)} bi</span><span>R$ ${fmt(c.volume,1)} bi</span><img class="arrow-icon" src="assets/chevron.svg"></div>`).join('')}
function renderStocks(list=D.stocks){$('#stocksTable').innerHTML=stockRows(list)}function renderCrypto(list=D.cryptos){$('#cryptoTable').innerHTML=cryptoRows(list)}
function renderRanking(type='gainers'){let list;if(type==='crypto'){list=[...D.cryptos].sort((a,b)=>b.change-a.change);$('#rankingTable').innerHTML=cryptoRows(list)}else{list=[...D.stocks];if(type==='gainers')list.sort((a,b)=>b.change-a.change);if(type==='losers')list.sort((a,b)=>a.change-b.change);if(type==='volume')list.sort((a,b)=>b.volume-a.volume);if(type==='dy')list.sort((a,b)=>b.dy-a.dy);if(type==='pe')list.sort((a,b)=>a.pe-b.pe);$('#rankingTable').innerHTML=stockRows(list)}}
function options(){return D.stocks.map(s=>`<option value="stock:${s.ticker}">${s.ticker}</option>`).concat(D.cryptos.map(c=>`<option value="crypto:${c.symbol}">${c.symbol}</option>`)).join('')}
function renderCompare(){const o=options();$('#compare1').innerHTML=o;$('#compare2').innerHTML=o;$('#compare3').innerHTML='<option value="">Nenhum</option>'+o;$('#compare1').value='stock:PETR4';$('#compare2').value='stock:VALE3';$('#compare3').value='crypto:BTC';drawCompare()}
function getAsset(key){const [kind,id]=key.split(':');return kind==='stock'?D.stocks.find(x=>x.ticker===id):D.cryptos.find(x=>x.symbol===id)}
function drawCompare(){const keys=[$('#compare1').value,$('#compare2').value,$('#compare3').value].filter(Boolean),colors=['#149c53','#2e68dc','#7655d8'];const assets=keys.map(getAsset);const series=assets.map(a=>{const first=a.intraday[0];return a.intraday.map(v=>(v/first-1)*100)});let min=Math.min(...series.flat()),max=Math.max(...series.flat()),w=760,h=360,p=28,range=max-min||1;let svg=`<svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none"><line x1="${p}" y1="${h-p}" x2="${w-p}" y2="${h-p}" stroke="#e1e7e3"/>`;series.forEach((arr,j)=>{let pts=arr.map((v,i)=>`${p+i*(w-2*p)/(arr.length-1)},${h-p-(v-min)*(h-2*p)/range}`).join(' ');svg+=`<polyline points="${pts}" fill="none" stroke="${colors[j]}" stroke-width="2.5" vector-effect="non-scaling-stroke"/>`});svg+='</svg>';$('#compareChart').innerHTML=svg;$('#compareLegend').className='compare-legend';$('#compareLegend').innerHTML=assets.map((a,i)=>`<span><i style="background:${colors[i]}"></i>${a.ticker||a.symbol}</span>`).join('')}
function renderCalendar(impact='all'){const list=impact==='all'?D.calendar:D.calendar.filter(e=>e.impact===impact);$('#calendarTable').innerHTML=`<div class="cal-head"><span>Data</span><span>Hora</span><span>Evento</span><span>País</span><span>Impacto</span><span>Projeção</span><span>Anterior</span></div>`+list.map(e=>`<div class="cal-row"><b>${e.date}</b><span>${e.time}</span><b>${e.event}</b><span>${e.country}</span><span class="impact ${e.impact}">${e.impact}</span><span>${e.forecast}</span><span>${e.previous}</span></div>`).join('')}
function renderNews(cat='all'){const list=cat==='all'?D.news:D.news.filter(n=>n.category===cat);$('#newsGrid').innerHTML=list.map(n=>`<article class="news-card"><img src="assets/news/${n.image}"><div class="news-body"><div class="news-meta"><span>${n.source}</span><time>${n.time}</time></div><h2>${n.title}</h2><p>${n.summary}</p><div class="news-tags"><span>${n.category}</span><span>${n.asset}</span></div><a href="${n.url}" target="_blank" rel="noopener noreferrer">Abrir fonte →</a></div></article>`).join('')}
function detail(kind,id){lastView=current;const a=kind==='stock'?D.stocks.find(x=>x.ticker===id):D.cryptos.find(x=>x.symbol===id);switchView('detail',false);const isStock=kind==='stock',title=isStock?a.ticker:a.symbol;$('#detailContent').innerHTML=`<div class="detail-hero"><article class="panel"><span class="eyebrow">${isStock?'AÇÃO · '+a.sector:'CRIPTOATIVO'}</span><h1>${title} <small>${a.name}</small></h1><div class="detail-price">${isStock?'R$ ':''}${fmt(a.price,a.price<1?6:2)}</div><b class="${a.change>=0?'positive':'negative'}">${a.change>=0?'+':''}${fmt(a.change)}%</b><div class="candles-toggle"><button class="active" data-chart="line">Linha</button><button data-chart="candle">Candles</button></div><div id="detailChart" class="detail-chart">${svgLine(a.intraday,a.change>=0?'#149c53':'#df3b43')}</div></article><article class="panel"><div class="panel-heading"><h2>Resumo do ativo</h2></div><div class="metric-cards"><div class="metric"><span>Abertura</span><b>${fmt(a.open||a.intraday[0],a.price<1?6:2)}</b></div><div class="metric"><span>Máxima</span><b>${fmt(a.high,a.price<1?6:2)}</b></div><div class="metric"><span>Mínima</span><b>${fmt(a.low,a.price<1?6:2)}</b></div><div class="metric"><span>Volume</span><b>${isStock?compact(a.volume):'R$ '+fmt(a.volume,1)+' bi'}</b></div><div class="metric"><span>Valor de mercado</span><b>R$ ${fmt(a.marketCap,1)} bi</b></div><div class="metric"><span>Máxima 52 sem.</span><b>${fmt(a.high52,a.price<1?6:2)}</b></div><div class="metric"><span>Mínima 52 sem.</span><b>${fmt(a.low52||a.low,a.price<1?6:2)}</b></div><div class="metric"><span>Horário de referência</span><b>${D.snapshotTime}</b></div></div></article></div>${isStock?`<article class="panel" style="margin-top:12px"><div class="panel-heading"><h2>Indicadores fundamentalistas</h2></div><div class="fundamentals" style="margin-top:12px"><div class="metric"><span>P/L</span><b>${fmt(a.pe)}</b></div><div class="metric"><span>P/VP</span><b>${fmt(a.pb)}</b></div><div class="metric"><span>Dívida / patrimônio</span><b>${fmt(a.debt)}</b></div><div class="metric"><span>Dividend Yield</span><b>${fmt(a.dy)}%</b></div><div class="metric"><span>Dividendos estimados</span><b>R$ ${fmt(a.dividends)}</b></div><div class="metric"><span>Setor</span><b>${a.sector}</b></div></div></article>`:''}`;$$('.candles-toggle button').forEach(b=>b.onclick=()=>{$$('.candles-toggle button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#detailChart').innerHTML=b.dataset.chart==='candle'?candles(a.intraday):svgLine(a.intraday,a.change>=0?'#149c53':'#df3b43')})}
function switchView(view,scroll=true){current=view;$$('.view').forEach(v=>v.classList.remove('active'));$('#'+view+'View').classList.add('active');$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));if(view==='stocks')renderStocks();if(view==='crypto')renderCrypto();if(view==='rankings')renderRanking();if(view==='compare')renderCompare();if(view==='calendar')renderCalendar();if(view==='news')renderNews();if(scroll)window.scrollTo({top:0,behavior:'smooth'})}
function simulate(){simStep++;const candidates=[...D.stocks.slice(0,8),...D.cryptos.slice(0,5)];candidates.forEach(a=>{const old=a.price,delta=(Math.sin(simStep*.7+a.price)*.00035)*a.price;a.price=Math.max(0,a.price+delta);const els=$$(`[data-detail$=":${a.ticker||a.symbol}"]`);els.forEach(el=>{el.classList.remove('flash-up','flash-down');void el.offsetWidth;el.classList.add(delta>=0?'flash-up':'flash-down')})});if(current==='stocks')renderStocks(filterStocks());if(current==='crypto')renderCrypto(filterCrypto());renderTapes();toast('Reprodução local atualizada · '+new Date().toLocaleTimeString('pt-BR'))}
function filterStocks(){let q=$('#stockSearch').value.toLowerCase(),list=D.stocks.filter(s=>(s.ticker+' '+s.name+' '+s.sector).toLowerCase().includes(q)),sort=$('#stockSort').value;if(sort==='volume')list.sort((a,b)=>b.volume-a.volume);if(sort==='change')list.sort((a,b)=>b.change-a.change);if(sort==='dy')list.sort((a,b)=>b.dy-a.dy);if(sort==='pe')list.sort((a,b)=>a.pe-b.pe);return list}function filterCrypto(){let q=$('#cryptoSearch').value.toLowerCase(),list=D.cryptos.filter(c=>(c.symbol+' '+c.name).toLowerCase().includes(q)),sort=$('#cryptoSort').value;list.sort((a,b)=>b[sort]-a[sort]);return list}
function search(q){q=q.trim().toLowerCase();const box=$('#searchResults');if(!q){box.classList.remove('show');return}const pool=[...D.stocks.map(x=>({kind:'stock',id:x.ticker,title:x.ticker,sub:x.name})),...D.cryptos.map(x=>({kind:'crypto',id:x.symbol,title:x.symbol,sub:x.name})),...D.indices.map(x=>({kind:'index',id:x.symbol,title:x.symbol,sub:x.name}))],found=pool.filter(x=>(x.title+' '+x.sub).toLowerCase().includes(q)).slice(0,10);box.innerHTML=found.length?found.map(x=>`<div class="search-result" data-search-kind="${x.kind}" data-search-id="${x.id}"><b>${x.title}</b><span>${x.sub}</span></div>`).join(''):'<div class="search-result">Nenhum ativo encontrado</div>';box.classList.add('show')}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>e.classList.remove('show'),1800)}
function renderTapes(){const items=[...D.indices,...D.currencies.slice(0,1),...D.cryptos.slice(0,5),...D.stocks.slice(0,7)];const cards=items.map(x=>`<div class="tape-item"><div><small>${x.symbol||x.ticker}</small><strong>${x.price>1000?fmt(x.price):fmt(x.price,x.price<1?6:2)} <span class="${x.change>=0?'positive':'negative'}">${x.change>=0?'+':''}${fmt(x.change)}%</span></strong></div><div class="mini-chart">${mini(x.intraday||[10,11,10,13,12,15,14,17],x.change>=0?'#149c53':'#df3b43')}</div></div>`).join('');$('#marketTape').innerHTML=`<div class="tape-track">${cards}${cards}</div>`;$('#headlineTape').textContent=D.news.map(n=>n.title).join('   •   ')}
document.addEventListener('DOMContentLoaded',()=>{$('#clock').textContent=D.snapshotTime;renderTapes();renderOverview();$$('.periods [data-period]').forEach(b=>b.addEventListener('click',()=>{$$('.periods [data-period]').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderOverviewPeriod(b.dataset.period)}));$$('[data-view]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();switchView(b.dataset.view)}));document.body.addEventListener('click',e=>{const d=e.target.closest('[data-detail]');if(d){const [k,id]=d.dataset.detail.split(':');detail(k,id)}});$('#detailBack').onclick=()=>switchView(lastView);$('#searchButton').onclick=()=>{$('.search').classList.add('open');$('#globalSearch').focus()};$('#searchClose').onclick=()=>{$('.search').classList.remove('open');$('#globalSearch').value='';$('#searchResults').classList.remove('show')};$('#globalSearch').oninput=e=>search(e.target.value);$('#searchResults').onclick=e=>{const r=e.target.closest('[data-search-kind]');if(!r)return;if(r.dataset.searchKind==='index'){switchView('overview')}else detail(r.dataset.searchKind,r.dataset.searchId);$('#searchResults').classList.remove('show')};$('#stockSearch').oninput=()=>renderStocks(filterStocks());$('#stockSort').onchange=()=>renderStocks(filterStocks());$('#cryptoSearch').oninput=()=>renderCrypto(filterCrypto());$('#cryptoSort').onchange=()=>renderCrypto(filterCrypto());$$('[data-ranking]').forEach(b=>b.onclick=()=>{$$('[data-ranking]').forEach(x=>x.classList.remove('active'));b.classList.add('active');showSkeleton('#rankingTable',()=>renderRanking(b.dataset.ranking))});$('#compareButton').onclick=drawCompare;$$('[data-impact]').forEach(b=>b.onclick=()=>{$$('[data-impact]').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderCalendar(b.dataset.impact)});$$('[data-category]').forEach(b=>b.onclick=()=>{$$('[data-category]').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderNews(b.dataset.category)});simulationTimer=setInterval(simulate,60000)})
